[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Over ons"
  url = "/over-ons/"
  weight = 2

[[main]]
  name = "Diensten"
  url = "/diensten/"
  weight = 3

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
