# Site-specifieke params
author = "Jouw Naam"
description = "Een snelle en SEO-vriendelijke website met Hugo, HTMX en Alpine.js."
keywords = ["hugo", "htmx", "alpine.js", "SEO", "staticsite"]
favicon = "images/favicon.ico"

[seo]
  enable = true
  twitter_card = "summary_large_image"
  og_image = "/images/og-image.png"

[schema]
  type = "Organization"
  name = "Voorbeeldbedrijf BV"
  url = "https://voorbeeldbedrijf.nl"
  logo = "/images/logo.png"
  sameAs = ["https://www.linkedin.com/company/voorbeeldbedrijf","https://twitter.com/voorbeeldbedrijf"]

# Social metadata (OpenGraph/Twitter)
social = [
  { name = "twitter", url = "https://twitter.com/jouwaccount" },
  { name = "facebook", url = "https://facebook.com/jouwaccount" }
]